#!/usr/bin/env python3
from twilio.rest import Client 
 
account_sid = '[Account_SID]'
auth_token = '[Auth Token]'
client = Client(account_sid, auth_token)

message = client.messages.create(
                              messaging_service_sid='[Your_ID]',
                              body='hi',
                              to='[Your_Number]'
                          )

print(message.sid)
